# Generated by Django 6.0.3 on 2026-04-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('platform_core', '0002_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Пометка удаления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('nomenclature_type', models.CharField(choices=[('goods', 'Товар'), ('service', 'Услуга'), ('work', 'Работа')], default='service', max_length=20, verbose_name='Вид номенклатуры')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Объём (м³)')),
                ('vat_rate', models.CharField(choices=[('none', 'Без НДС'), ('0', '0%'), ('10', '10%'), ('20', '20%')], default='none', max_length=10, verbose_name='Ставка НДС')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='nomenclature.nomenclature', verbose_name='Родитель')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.unitofmeasure', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Вид цены',
                'verbose_name_plural': 'Виды цен',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PriceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('period', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Период')),
                ('recorder_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID регистратора')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Цена')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.currency', verbose_name='Валюта')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('recorder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Тип регистратора')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='nomenclature.pricetype', verbose_name='Вид цены')),
            ],
            options={
                'verbose_name': 'Цена номенклатуры',
                'verbose_name_plural': 'Цены номенклатуры',
                'ordering': ['-period'],
            },
        ),
    ]
