# Generated by Django 6.0.3 on 2026-04-20 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0001_initial'),
        ('nomenclature', '0001_initial'),
        ('orders', '0001_initial'),
        ('platform_core', '0002_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order', verbose_name='Заказ-основание'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Провёл'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Счёт'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='payment',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='payment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Провёл'),
        ),
        migrations.AddField(
            model_name='settlementsregister',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_movements', to='counterparties.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='settlementsregister',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_movements', to='counterparties.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='settlementsregister',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_movements', to='counterparties.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='settlementsregister',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='settlementsregister',
            name='recorder_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Тип регистратора'),
        ),
        migrations.AddIndex(
            model_name='settlementsregister',
            index=models.Index(fields=['organization', 'client', 'period'], name='billing_set_organiz_e049cc_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementsregister',
            index=models.Index(fields=['organization', 'counterparty', 'contract', 'period'], name='billing_set_organiz_4362db_idx'),
        ),
    ]
