# Generated by Django 6.0.3 on 2026-04-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, verbose_name='Модуль (app label)')),
                ('is_visible', models.BooleanField(default=False, help_text='Администратор платформы выдал доступ — организация видит модуль', verbose_name='Виден организации')),
                ('is_enabled', models.BooleanField(default=False, help_text='Модуль активен для организации', verbose_name='Включён')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='platform_core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Модуль организации',
                'verbose_name_plural': 'Модули организаций',
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
