# Generated by Django 6.0.3 on 2026-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bik', models.CharField(max_length=9, unique=True, verbose_name='БИК')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
    ]
