# Generated by Django 6.0.3 on 2026-04-16 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название / ФИО')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Мета-клиент',
                'verbose_name_plural': 'Мета-клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text='Только для отображения. Права определяются ролями.', max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Разрешает вход в панель платформы. Только для суперпользователей.', verbose_name='Доступ к platform_admin'),
        ),
        migrations.CreateModel(
            name='MetaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('permissions', models.ManyToManyField(blank=True, related_name='meta_roles', to='auth.permission', verbose_name='Права по умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон роли',
                'verbose_name_plural': 'Шаблоны ролей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSettingDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, verbose_name='Модуль (app label)')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('value_type', models.CharField(choices=[('string', 'Строка'), ('int', 'Целое число'), ('bool', 'Да/Нет'), ('json', 'JSON')], default='string', max_length=10, verbose_name='Тип значения')),
                ('default_value', models.TextField(help_text='JSON-encoded. Например: "hello", 42, true, {"key": "val"}', verbose_name='Значение по умолчанию')),
            ],
            options={
                'verbose_name': 'Определение настройки модуля',
                'verbose_name_plural': 'Определения настроек модулей',
                'ordering': ['module', 'key'],
                'unique_together': {('module', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('imported_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_roles', to='platform_core.metarole', verbose_name='Импортирована из шаблона')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='platform_core.organization', verbose_name='Организация')),
                ('permissions', models.ManyToManyField(blank=True, related_name='org_roles', to='auth.permission', verbose_name='Права')),
            ],
            options={
                'verbose_name': 'Роль организации',
                'verbose_name_plural': 'Роли организаций',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', to='platform_core.orgrole', verbose_name='Роли'),
        ),
        migrations.CreateModel(
            name='MetaClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(help_text='ID записи в таблице clients.Client', verbose_name='ID клиента')),
                ('meta_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='platform_core.metaclient', verbose_name='Мета-клиент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Связка мета-клиент',
                'verbose_name_plural': 'Связки мета-клиентов',
                'unique_together': {('organization', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, verbose_name='Модуль (app label)')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ')),
                ('value', models.TextField(help_text='JSON-encoded', verbose_name='Значение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_settings', to='platform_core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Настройка организации',
                'verbose_name_plural': 'Настройки организаций',
                'ordering': ['organization', 'module', 'key'],
                'unique_together': {('organization', 'module', 'key')},
            },
        ),
    ]
