# Generated by Django 6.0.3 on 2026-04-15 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('legal', 'Юридическое лицо'), ('individual', 'Физическое лицо')], default='legal', max_length=20, verbose_name='Тип клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Название / ФИО')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='platform_core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
                'unique_together': {('organization', 'inn')},
            },
        ),
        migrations.CreateModel(
            name='ClientObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_objects', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Объект клиента',
                'verbose_name_plural': 'Объекты клиентов',
                'ordering': ['client', 'name'],
            },
        ),
    ]
