# Generated by Django 6.0.3 on 2026-04-16 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='platform_core.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='clientobject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_objects', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('organization', 'inn')},
        ),
    ]
