# Generated by Django 6.0.3 on 2026-04-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_core', '0002_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Пометка удаления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('counterparty_type', models.CharField(choices=[('legal', 'Юридическое лицо'), ('ie', 'Индивидуальный предприниматель'), ('individual', 'Физическое лицо')], default='legal', max_length=20, verbose_name='Тип контрагента')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='counterparties.counterparty', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Пометка удаления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('contract_type', models.CharField(choices=[('buyer', 'С покупателем'), ('supplier', 'С поставщиком'), ('other', 'Прочее')], default='buyer', max_length=20, verbose_name='Вид договора')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='counterparties.contract', verbose_name='Родитель')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='counterparties.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Пометка удаления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='counterparties.client', verbose_name='Родитель')),
                ('counterparties', models.ManyToManyField(blank=True, related_name='clients', to='counterparties.counterparty', verbose_name='Контрагенты')),
                ('main_counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='counterparties.counterparty', verbose_name='Основной контрагент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('account_number', models.CharField(max_length=20, verbose_name='Номер счёта')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.bank', verbose_name='Банк')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='counterparties.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
                'ordering': ['-is_main', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Пометка удаления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='counterparties.individual', verbose_name='Физическое лицо'),
        ),
    ]
