# Generated by Django 6.0.3 on 2026-04-20 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0001_initial'),
        ('nomenclature', '0001_initial'),
        ('platform_core', '0002_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order_status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('delivered', 'Выдан'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='counterparties.client', verbose_name='Клиент')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='counterparties.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='counterparties.counterparty', verbose_name='Контрагент')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.currency', verbose_name='Валюта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Провёл')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Скидка (%)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма')),
                ('vat_rate', models.CharField(blank=True, max_length=10, verbose_name='Ставка НДС')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Сумма НДС')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_core.unitofmeasure', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrdersRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('period', models.DateTimeField(db_index=True, verbose_name='Период')),
                ('recorder_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID регистратора')),
                ('activity', models.BooleanField(default=True, verbose_name='Приход (True) / Расход (False)')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_movements', to='counterparties.client', verbose_name='Клиент')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_movements', to='nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='platform_core.organization', verbose_name='Организация')),
                ('recorder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Тип регистратора')),
            ],
            options={
                'verbose_name': 'Движение по заказам',
                'verbose_name_plural': 'Движения по заказам',
                'indexes': [models.Index(fields=['organization', 'client', 'period'], name='orders_orde_organiz_c0eae1_idx'), models.Index(fields=['organization', 'nomenclature', 'period'], name='orders_orde_organiz_104e0a_idx')],
            },
        ),
    ]
